services:
  db:
    image: mysql:8.0
    container_name: mysql_funcionarios
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_funcionarios
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: api_funcionarios
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=sistema_funcionarios;User=root;Password=root;"
    ports:
      - "8080:8080"

volumes:
  mysql_data: